/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVerifiedRouteRouteImport } from './routes/_authenticated/_verified/route'
import { Route as ApiPublicFirebaseConfigRouteImport } from './routes/api/public/firebase-config'
import { Route as AuthenticatedVerifiedMessagesRouteImport } from './routes/_authenticated/_verified/messages'
import { Route as AuthenticatedVerifiedMessagesIndexRouteImport } from './routes/_authenticated/_verified/messages.index'
import { Route as AuthenticatedVerifiedSettingsNotificationsRouteImport } from './routes/_authenticated/_verified/settings.notifications'
import { Route as AuthenticatedVerifiedMessagesNewRouteImport } from './routes/_authenticated/_verified/messages.new'
import { Route as AuthenticatedVerifiedMessagesThreadIdRouteImport } from './routes/_authenticated/_verified/messages.$threadId'
import { Route as AuthenticatedVerifiedForumNewRouteImport } from './routes/_authenticated/_verified/forum.new'
import { Route as AuthenticatedVerifiedEventsEventIdCheckoutRouteImport } from './routes/_authenticated/_verified/events.$eventId.checkout'

const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVerifiedRouteRoute =
  AuthenticatedVerifiedRouteRouteImport.update({
    id: '/_verified',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicFirebaseConfigRoute = ApiPublicFirebaseConfigRouteImport.update({
  id: '/api/public/firebase-config',
  path: '/api/public/firebase-config',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVerifiedMessagesRoute =
  AuthenticatedVerifiedMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedVerifiedRouteRoute,
  } as any)
const AuthenticatedVerifiedMessagesIndexRoute =
  AuthenticatedVerifiedMessagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVerifiedMessagesRoute,
  } as any)
const AuthenticatedVerifiedSettingsNotificationsRoute =
  AuthenticatedVerifiedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedVerifiedRouteRoute,
  } as any)
const AuthenticatedVerifiedMessagesNewRoute =
  AuthenticatedVerifiedMessagesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedVerifiedMessagesRoute,
  } as any)
const AuthenticatedVerifiedMessagesThreadIdRoute =
  AuthenticatedVerifiedMessagesThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedVerifiedMessagesRoute,
  } as any)
const AuthenticatedVerifiedForumNewRoute =
  AuthenticatedVerifiedForumNewRouteImport.update({
    id: '/forum/new',
    path: '/forum/new',
    getParentRoute: () => AuthenticatedVerifiedRouteRoute,
  } as any)
const AuthenticatedVerifiedEventsEventIdCheckoutRoute =
  AuthenticatedVerifiedEventsEventIdCheckoutRouteImport.update({
    id: '/events/$eventId/checkout',
    path: '/events/$eventId/checkout',
    getParentRoute: () => AuthenticatedVerifiedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof AuthenticatedVerifiedMessagesRouteWithChildren
  '/api/public/firebase-config': typeof ApiPublicFirebaseConfigRoute
  '/forum/new': typeof AuthenticatedVerifiedForumNewRoute
  '/messages/$threadId': typeof AuthenticatedVerifiedMessagesThreadIdRoute
  '/messages/new': typeof AuthenticatedVerifiedMessagesNewRoute
  '/settings/notifications': typeof AuthenticatedVerifiedSettingsNotificationsRoute
  '/messages/': typeof AuthenticatedVerifiedMessagesIndexRoute
  '/events/$eventId/checkout': typeof AuthenticatedVerifiedEventsEventIdCheckoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/marketplace': typeof MarketplaceRoute
  '/api/public/firebase-config': typeof ApiPublicFirebaseConfigRoute
  '/forum/new': typeof AuthenticatedVerifiedForumNewRoute
  '/messages/$threadId': typeof AuthenticatedVerifiedMessagesThreadIdRoute
  '/messages/new': typeof AuthenticatedVerifiedMessagesNewRoute
  '/settings/notifications': typeof AuthenticatedVerifiedSettingsNotificationsRoute
  '/messages': typeof AuthenticatedVerifiedMessagesIndexRoute
  '/events/$eventId/checkout': typeof AuthenticatedVerifiedEventsEventIdCheckoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/discover': typeof DiscoverRoute
  '/marketplace': typeof MarketplaceRoute
  '/_authenticated/_verified': typeof AuthenticatedVerifiedRouteRouteWithChildren
  '/_authenticated/_verified/messages': typeof AuthenticatedVerifiedMessagesRouteWithChildren
  '/api/public/firebase-config': typeof ApiPublicFirebaseConfigRoute
  '/_authenticated/_verified/forum/new': typeof AuthenticatedVerifiedForumNewRoute
  '/_authenticated/_verified/messages/$threadId': typeof AuthenticatedVerifiedMessagesThreadIdRoute
  '/_authenticated/_verified/messages/new': typeof AuthenticatedVerifiedMessagesNewRoute
  '/_authenticated/_verified/settings/notifications': typeof AuthenticatedVerifiedSettingsNotificationsRoute
  '/_authenticated/_verified/messages/': typeof AuthenticatedVerifiedMessagesIndexRoute
  '/_authenticated/_verified/events/$eventId/checkout': typeof AuthenticatedVerifiedEventsEventIdCheckoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/discover'
    | '/marketplace'
    | '/messages'
    | '/api/public/firebase-config'
    | '/forum/new'
    | '/messages/$threadId'
    | '/messages/new'
    | '/settings/notifications'
    | '/messages/'
    | '/events/$eventId/checkout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/discover'
    | '/marketplace'
    | '/api/public/firebase-config'
    | '/forum/new'
    | '/messages/$threadId'
    | '/messages/new'
    | '/settings/notifications'
    | '/messages'
    | '/events/$eventId/checkout'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/discover'
    | '/marketplace'
    | '/_authenticated/_verified'
    | '/_authenticated/_verified/messages'
    | '/api/public/firebase-config'
    | '/_authenticated/_verified/forum/new'
    | '/_authenticated/_verified/messages/$threadId'
    | '/_authenticated/_verified/messages/new'
    | '/_authenticated/_verified/settings/notifications'
    | '/_authenticated/_verified/messages/'
    | '/_authenticated/_verified/events/$eventId/checkout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DiscoverRoute: typeof DiscoverRoute
  MarketplaceRoute: typeof MarketplaceRoute
  ApiPublicFirebaseConfigRoute: typeof ApiPublicFirebaseConfigRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_verified': {
      id: '/_authenticated/_verified'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedVerifiedRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/firebase-config': {
      id: '/api/public/firebase-config'
      path: '/api/public/firebase-config'
      fullPath: '/api/public/firebase-config'
      preLoaderRoute: typeof ApiPublicFirebaseConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_verified/messages': {
      id: '/_authenticated/_verified/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedVerifiedMessagesRouteImport
      parentRoute: typeof AuthenticatedVerifiedRouteRoute
    }
    '/_authenticated/_verified/messages/': {
      id: '/_authenticated/_verified/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedVerifiedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedVerifiedMessagesRoute
    }
    '/_authenticated/_verified/settings/notifications': {
      id: '/_authenticated/_verified/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedVerifiedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedVerifiedRouteRoute
    }
    '/_authenticated/_verified/messages/new': {
      id: '/_authenticated/_verified/messages/new'
      path: '/new'
      fullPath: '/messages/new'
      preLoaderRoute: typeof AuthenticatedVerifiedMessagesNewRouteImport
      parentRoute: typeof AuthenticatedVerifiedMessagesRoute
    }
    '/_authenticated/_verified/messages/$threadId': {
      id: '/_authenticated/_verified/messages/$threadId'
      path: '/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof AuthenticatedVerifiedMessagesThreadIdRouteImport
      parentRoute: typeof AuthenticatedVerifiedMessagesRoute
    }
    '/_authenticated/_verified/forum/new': {
      id: '/_authenticated/_verified/forum/new'
      path: '/forum/new'
      fullPath: '/forum/new'
      preLoaderRoute: typeof AuthenticatedVerifiedForumNewRouteImport
      parentRoute: typeof AuthenticatedVerifiedRouteRoute
    }
    '/_authenticated/_verified/events/$eventId/checkout': {
      id: '/_authenticated/_verified/events/$eventId/checkout'
      path: '/events/$eventId/checkout'
      fullPath: '/events/$eventId/checkout'
      preLoaderRoute: typeof AuthenticatedVerifiedEventsEventIdCheckoutRouteImport
      parentRoute: typeof AuthenticatedVerifiedRouteRoute
    }
  }
}

interface AuthenticatedVerifiedMessagesRouteChildren {
  AuthenticatedVerifiedMessagesThreadIdRoute: typeof AuthenticatedVerifiedMessagesThreadIdRoute
  AuthenticatedVerifiedMessagesNewRoute: typeof AuthenticatedVerifiedMessagesNewRoute
  AuthenticatedVerifiedMessagesIndexRoute: typeof AuthenticatedVerifiedMessagesIndexRoute
}

const AuthenticatedVerifiedMessagesRouteChildren: AuthenticatedVerifiedMessagesRouteChildren =
  {
    AuthenticatedVerifiedMessagesThreadIdRoute:
      AuthenticatedVerifiedMessagesThreadIdRoute,
    AuthenticatedVerifiedMessagesNewRoute:
      AuthenticatedVerifiedMessagesNewRoute,
    AuthenticatedVerifiedMessagesIndexRoute:
      AuthenticatedVerifiedMessagesIndexRoute,
  }

const AuthenticatedVerifiedMessagesRouteWithChildren =
  AuthenticatedVerifiedMessagesRoute._addFileChildren(
    AuthenticatedVerifiedMessagesRouteChildren,
  )

interface AuthenticatedVerifiedRouteRouteChildren {
  AuthenticatedVerifiedMessagesRoute: typeof AuthenticatedVerifiedMessagesRouteWithChildren
  AuthenticatedVerifiedForumNewRoute: typeof AuthenticatedVerifiedForumNewRoute
  AuthenticatedVerifiedSettingsNotificationsRoute: typeof AuthenticatedVerifiedSettingsNotificationsRoute
  AuthenticatedVerifiedEventsEventIdCheckoutRoute: typeof AuthenticatedVerifiedEventsEventIdCheckoutRoute
}

const AuthenticatedVerifiedRouteRouteChildren: AuthenticatedVerifiedRouteRouteChildren =
  {
    AuthenticatedVerifiedMessagesRoute:
      AuthenticatedVerifiedMessagesRouteWithChildren,
    AuthenticatedVerifiedForumNewRoute: AuthenticatedVerifiedForumNewRoute,
    AuthenticatedVerifiedSettingsNotificationsRoute:
      AuthenticatedVerifiedSettingsNotificationsRoute,
    AuthenticatedVerifiedEventsEventIdCheckoutRoute:
      AuthenticatedVerifiedEventsEventIdCheckoutRoute,
  }

const AuthenticatedVerifiedRouteRouteWithChildren =
  AuthenticatedVerifiedRouteRoute._addFileChildren(
    AuthenticatedVerifiedRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedVerifiedRouteRoute: typeof AuthenticatedVerifiedRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedVerifiedRouteRoute: AuthenticatedVerifiedRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DiscoverRoute: DiscoverRoute,
  MarketplaceRoute: MarketplaceRoute,
  ApiPublicFirebaseConfigRoute: ApiPublicFirebaseConfigRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
