/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVerifiedRouteRouteImport } from './routes/_authenticated/_verified/route'
import { Route as AuthenticatedVerifiedMessagesRouteImport } from './routes/_authenticated/_verified/messages'
import { Route as AuthenticatedVerifiedMessagesNewRouteImport } from './routes/_authenticated/_verified/messages.new'
import { Route as AuthenticatedVerifiedMessagesThreadIdRouteImport } from './routes/_authenticated/_verified/messages.$threadId'
import { Route as AuthenticatedVerifiedForumNewRouteImport } from './routes/_authenticated/_verified/forum.new'
import { Route as AuthenticatedVerifiedEventsEventIdCheckoutRouteImport } from './routes/_authenticated/_verified/events.$eventId.checkout'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVerifiedRouteRoute =
  AuthenticatedVerifiedRouteRouteImport.update({
    id: '/_verified',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVerifiedMessagesRoute =
  AuthenticatedVerifiedMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedVerifiedRouteRoute,
  } as any)
const AuthenticatedVerifiedMessagesNewRoute =
  AuthenticatedVerifiedMessagesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedVerifiedMessagesRoute,
  } as any)
const AuthenticatedVerifiedMessagesThreadIdRoute =
  AuthenticatedVerifiedMessagesThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedVerifiedMessagesRoute,
  } as any)
const AuthenticatedVerifiedForumNewRoute =
  AuthenticatedVerifiedForumNewRouteImport.update({
    id: '/forum/new',
    path: '/forum/new',
    getParentRoute: () => AuthenticatedVerifiedRouteRoute,
  } as any)
const AuthenticatedVerifiedEventsEventIdCheckoutRoute =
  AuthenticatedVerifiedEventsEventIdCheckoutRouteImport.update({
    id: '/events/$eventId/checkout',
    path: '/events/$eventId/checkout',
    getParentRoute: () => AuthenticatedVerifiedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/messages': typeof AuthenticatedVerifiedMessagesRouteWithChildren
  '/forum/new': typeof AuthenticatedVerifiedForumNewRoute
  '/messages/$threadId': typeof AuthenticatedVerifiedMessagesThreadIdRoute
  '/messages/new': typeof AuthenticatedVerifiedMessagesNewRoute
  '/events/$eventId/checkout': typeof AuthenticatedVerifiedEventsEventIdCheckoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/messages': typeof AuthenticatedVerifiedMessagesRouteWithChildren
  '/forum/new': typeof AuthenticatedVerifiedForumNewRoute
  '/messages/$threadId': typeof AuthenticatedVerifiedMessagesThreadIdRoute
  '/messages/new': typeof AuthenticatedVerifiedMessagesNewRoute
  '/events/$eventId/checkout': typeof AuthenticatedVerifiedEventsEventIdCheckoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_verified': typeof AuthenticatedVerifiedRouteRouteWithChildren
  '/_authenticated/_verified/messages': typeof AuthenticatedVerifiedMessagesRouteWithChildren
  '/_authenticated/_verified/forum/new': typeof AuthenticatedVerifiedForumNewRoute
  '/_authenticated/_verified/messages/$threadId': typeof AuthenticatedVerifiedMessagesThreadIdRoute
  '/_authenticated/_verified/messages/new': typeof AuthenticatedVerifiedMessagesNewRoute
  '/_authenticated/_verified/events/$eventId/checkout': typeof AuthenticatedVerifiedEventsEventIdCheckoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/messages'
    | '/forum/new'
    | '/messages/$threadId'
    | '/messages/new'
    | '/events/$eventId/checkout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/messages'
    | '/forum/new'
    | '/messages/$threadId'
    | '/messages/new'
    | '/events/$eventId/checkout'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_verified'
    | '/_authenticated/_verified/messages'
    | '/_authenticated/_verified/forum/new'
    | '/_authenticated/_verified/messages/$threadId'
    | '/_authenticated/_verified/messages/new'
    | '/_authenticated/_verified/events/$eventId/checkout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_verified': {
      id: '/_authenticated/_verified'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedVerifiedRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_verified/messages': {
      id: '/_authenticated/_verified/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedVerifiedMessagesRouteImport
      parentRoute: typeof AuthenticatedVerifiedRouteRoute
    }
    '/_authenticated/_verified/messages/new': {
      id: '/_authenticated/_verified/messages/new'
      path: '/new'
      fullPath: '/messages/new'
      preLoaderRoute: typeof AuthenticatedVerifiedMessagesNewRouteImport
      parentRoute: typeof AuthenticatedVerifiedMessagesRoute
    }
    '/_authenticated/_verified/messages/$threadId': {
      id: '/_authenticated/_verified/messages/$threadId'
      path: '/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof AuthenticatedVerifiedMessagesThreadIdRouteImport
      parentRoute: typeof AuthenticatedVerifiedMessagesRoute
    }
    '/_authenticated/_verified/forum/new': {
      id: '/_authenticated/_verified/forum/new'
      path: '/forum/new'
      fullPath: '/forum/new'
      preLoaderRoute: typeof AuthenticatedVerifiedForumNewRouteImport
      parentRoute: typeof AuthenticatedVerifiedRouteRoute
    }
    '/_authenticated/_verified/events/$eventId/checkout': {
      id: '/_authenticated/_verified/events/$eventId/checkout'
      path: '/events/$eventId/checkout'
      fullPath: '/events/$eventId/checkout'
      preLoaderRoute: typeof AuthenticatedVerifiedEventsEventIdCheckoutRouteImport
      parentRoute: typeof AuthenticatedVerifiedRouteRoute
    }
  }
}

interface AuthenticatedVerifiedMessagesRouteChildren {
  AuthenticatedVerifiedMessagesThreadIdRoute: typeof AuthenticatedVerifiedMessagesThreadIdRoute
  AuthenticatedVerifiedMessagesNewRoute: typeof AuthenticatedVerifiedMessagesNewRoute
}

const AuthenticatedVerifiedMessagesRouteChildren: AuthenticatedVerifiedMessagesRouteChildren =
  {
    AuthenticatedVerifiedMessagesThreadIdRoute:
      AuthenticatedVerifiedMessagesThreadIdRoute,
    AuthenticatedVerifiedMessagesNewRoute:
      AuthenticatedVerifiedMessagesNewRoute,
  }

const AuthenticatedVerifiedMessagesRouteWithChildren =
  AuthenticatedVerifiedMessagesRoute._addFileChildren(
    AuthenticatedVerifiedMessagesRouteChildren,
  )

interface AuthenticatedVerifiedRouteRouteChildren {
  AuthenticatedVerifiedMessagesRoute: typeof AuthenticatedVerifiedMessagesRouteWithChildren
  AuthenticatedVerifiedForumNewRoute: typeof AuthenticatedVerifiedForumNewRoute
  AuthenticatedVerifiedEventsEventIdCheckoutRoute: typeof AuthenticatedVerifiedEventsEventIdCheckoutRoute
}

const AuthenticatedVerifiedRouteRouteChildren: AuthenticatedVerifiedRouteRouteChildren =
  {
    AuthenticatedVerifiedMessagesRoute:
      AuthenticatedVerifiedMessagesRouteWithChildren,
    AuthenticatedVerifiedForumNewRoute: AuthenticatedVerifiedForumNewRoute,
    AuthenticatedVerifiedEventsEventIdCheckoutRoute:
      AuthenticatedVerifiedEventsEventIdCheckoutRoute,
  }

const AuthenticatedVerifiedRouteRouteWithChildren =
  AuthenticatedVerifiedRouteRoute._addFileChildren(
    AuthenticatedVerifiedRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedVerifiedRouteRoute: typeof AuthenticatedVerifiedRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedVerifiedRouteRoute: AuthenticatedVerifiedRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
